version: '3.7'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: django_example
      POSTGRES_PASSWORD: django_example
      POSTGRES_DB: django_example_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "./start.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=<YOUR_KEY_HERE>
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=<YOUR_APP_SECRET_HERE>
    depends_on:
      - db
volumes:
  pgdata: